### PR TITLE
Delete Index.js

### PR DESCRIPTION
**Pull request by AJ-7885**
The build folder dose not need to be commit it . Do you have any reason to push it ?

### CODE REVIEW

**Comment by jchavarri** [comment]
Right, do you think you could add an update to the `.gitignore` file so these files don't get committed again in the future?

**Comment by AJ-7885** [comment]
sure , I will be happy to do it.

**Comment by AJ-7885** [comment]
https://github.com/jchavarri/example-bsb-jest-es6/pull/3

**Comment by jchavarri** [comment]
thanks!

**Pull request merged**
